name: CallShift CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Unit Tests
      run: ./gradlew :app:testStandardDebugUnitTest --no-daemon

    - name: Build Standard Release & Debug APKs
      run: ./gradlew :app:assembleStandardRelease :app:assembleStandardDebug --no-daemon

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: CallShift-release-apk
        path: app/build/outputs/apk/standard/release/*.apk

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: CallShift-debug-apk
        path: app/build/outputs/apk/standard/debug/*.apk
